version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    environment:
      POSTGRES_DB: erpdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: