server:
  port: ${PORTA:8085}

spring:
  application:
    name: erp
  datasource:
    url: jdbc:postgresql://localhost:5432/erpdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.xml
  devtools:
    restart:
      enabled: true
      additional:
        - classpath:/src/main/resources/
        - classpath:/src/main/java/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html